#!/bin/bash

DEVICE=NULL;

date >> /var/log/shuttled.log

if [[ -z "$1" ]]
then 
	echo "Usage: shuttlerun <short_name>";
	exit 1;
fi

if [[ "$1" == "Pro" ]]
then
	DEVICE="usb-Contour_Design_ShuttlePRO_v2-event-if00"
elif [[ "$1" == "Space" ]]
then
	DEVICE="usb-CAVS_SpaceShuttle_A_V-event-if00"
elif [[ "$1" == "Xpress" ]]
then
	DEVICE="usb-Contour_Design_ShuttleXpress-event-if00"
else
	echo "Device must be Pro, Space or Xpress";
	exit 1;
fi
	
/usr/local/bin/shuttled /dev/input/by-id/$DEVICE >> /var/log/shuttled.log 2>&1
